### ISSUE TITLE
Customize colors in the website's CSS

### ISSUE THREAD

**Issue by emmet0r** [emmet0r/git-playground#8]
Update the website to use a Santa Cruz inspired color scheme.

While you're at it, could you also suggest some minor CSS changes to improve the layout...?

**Comment by Jordin221** [comment]
i got this one

**Comment by Jordin221** [comment]
@Jordin221 @https://github.com/klbynum

**Comment by Jordin221** [comment]
@klbynum @Jordin221

**Comment by Jordin221** [comment]
closed #8

**Comment by SilasVM** [comment]
Closed by pr #7
